export const SUBMIT_PRICING_VARIABLES = 'SUBMIT_PRICING_VARIABLES';
export const CHANGE_CHECKIN_DATE = 'CHANGE_CHECKIN_DATE';
export const CHANGE_CHECKOUT_DATE = 'CHANGE_CHECKOUT_DATE';
export const CHANGE_GUEST = 'CHANGE_GUEST';